"""Enum added

Revision ID: 29d61cb90460
Revises: 9edee9d01705
Create Date: 2024-02-25 16:45:00.077572

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '29d61cb90460'
down_revision: Union[str, None] = '9edee9d01705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.Enum('PLANNED', 'RECRUITMENT_OPENED', 'IN_PROGRESS', 'MVP_OPENED', 'COMPLETED', name='enumstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'status')
    # ### end Alembic commands ###
