"""Fixed issues in relationships

Revision ID: 2e086146ba05
Revises: 2ceeda8b2f15
Create Date: 2024-02-26 06:09:07.982089

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e086146ba05'
down_revision: Union[str, None] = '2ceeda8b2f15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_projects', sa.Column('datetime_joined', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('users_projects', 'datatime_joined')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_projects', sa.Column('datatime_joined', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('users_projects', 'datetime_joined')
    # ### end Alembic commands ###
