"""refactored models

Revision ID: 38f63347aedc
Revises: 04dd7d53eeff
Create Date: 2024-02-29 13:58:56.026017

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38f63347aedc'
down_revision: Union[str, None] = '04dd7d53eeff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_categories_id', table_name='categories')
    op.drop_index('ix_projects_id', table_name='projects')
    op.drop_index('ix_resources_id', table_name='resources')
    op.drop_index('ix_tokens_id', table_name='tokens')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_projects_id', table_name='users_projects')
    op.drop_column('users_projects', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_projects', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_users_projects_id', 'users_projects', ['id'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_tokens_id', 'tokens', ['id'], unique=False)
    op.create_index('ix_resources_id', 'resources', ['id'], unique=False)
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.create_index('ix_categories_id', 'categories', ['id'], unique=False)
    # ### end Alembic commands ###
