"""Fixed issues in relationships

Revision ID: 3e703415218b
Revises: 2e086146ba05
Create Date: 2024-02-26 10:31:52.051054

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3e703415218b'
down_revision: Union[str, None] = '2e086146ba05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_projects_project_id'), 'users_projects', ['project_id'], unique=True)
    op.create_index(op.f('ix_users_projects_user_id'), 'users_projects', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_projects_user_id'), table_name='users_projects')
    op.drop_index(op.f('ix_users_projects_project_id'), table_name='users_projects')
    # ### end Alembic commands ###
