"""Changes to model

Revision ID: 5d369a342f1b
Revises: 265536277fea
Create Date: 2024-02-28 15:15:20.072212

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5d369a342f1b'
down_revision: Union[str, None] = '265536277fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_projects_project_id', table_name='users_projects')
    op.drop_index('ix_users_projects_user_id', table_name='users_projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_projects_user_id', 'users_projects', ['user_id'], unique=True)
    op.create_index('ix_users_projects_project_id', 'users_projects', ['project_id'], unique=True)
    # ### end Alembic commands ###
