"""Token Model

Revision ID: c969878e5bae
Revises: a4baa4cb8557
Create Date: 2024-02-13 07:19:31.221454

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c969878e5bae"
down_revision: str | None = "a4baa4cb8557"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tokens_access_token"), "tokens", ["access_token"], unique=True
    )
    op.create_index(op.f("ix_tokens_id"), "tokens", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tokens_id"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_access_token"), table_name="tokens")
    op.drop_table("tokens")
    # ### end Alembic commands ###
