"""Fixed issues in relationships

Revision ID: caf1922f29a2
Revises: f63262dc7539
Create Date: 2024-02-26 05:29:27.120487

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'caf1922f29a2'
down_revision: Union[str, None] = 'f63262dc7539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
