"""Fixed issues in relationships

Revision ID: e496fdc49b99
Revises: 96dd797d3869
Create Date: 2024-02-26 11:14:58.975740

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e496fdc49b99'
down_revision: Union[str, None] = '96dd797d3869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
