"""Refactored relationships

Revision ID: f4678b8ce0c7
Revises: 29d61cb90460
Create Date: 2024-02-25 16:50:11.154810

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4678b8ce0c7'
down_revision: Union[str, None] = '29d61cb90460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_projects', sa.Column('datatime_joined', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users_projects', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('users_projects', 'is_author',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_users_projects_id'), 'users_projects', ['id'], unique=False)
    op.drop_column('users_projects', 'datetime_joined')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_projects', sa.Column('datetime_joined', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_projects_id'), table_name='users_projects')
    op.alter_column('users_projects', 'is_author',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('users_projects', 'id')
    op.drop_column('users_projects', 'datatime_joined')
    # ### end Alembic commands ###
