"""Fixed issues in relationships

Revision ID: f63262dc7539
Revises: f4678b8ce0c7
Create Date: 2024-02-26 05:22:34.228016

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f63262dc7539'
down_revision: Union[str, None] = 'f4678b8ce0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
